### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by watermelonhit** [kingyuluk/FlappyBird#11]
Hello!
I have some problem !just as 
I ran"F:\amusement\fun-1\FlappyBird>java -jar FlappyBird.jar"
but happened:
`Caused by: java.lang.ClassNotFoundException: sun.audio.AudioStream
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 36 more`

**Comment by ZuyuZhong** [comment]
> Hello!
> I have some problem !just as
> I ran"F:\amusement\fun-1\FlappyBird>java -jar FlappyBird.jar"
> but happened:
> `Caused by: java.lang.ClassNotFoundException: sun.audio.AudioStream at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ... 36 more`

me too

**Comment by kingyuluk** [comment]
plesea run on jdk1.8
