### ISSUE TITLE
repaint() 与 update()

### ISSUE THREAD

**Issue by Yangxiaohan0120** [kingyuluk/FlappyBird#14]
> repaint(); // 通过调用repaint(),让JVM调用update()

您好，看了您的代码，写的非常棒，我想知道这个地方使用repaint(),让JVM调用update()是什么意思呢？

**Comment by kingyuluk** [comment]
repaint()内部会调用update()方法来重绘，这两个方法的区别可以看看别人博客的介绍

**Comment by Yangxiaohan0120** [comment]
好的好的，感谢！
