### ISSUE TITLE
Interested to have Reinforcement Learning feature inside?

### ISSUE THREAD

**Issue by lanking520** [kingyuluk/FlappyBird#6]
Hi,

I came across your Flappy Bird project and feel like it's a good chance to get it automated to train for a Reinforcement Learning Agent. You can use DQN to have RL inside to play the game for you. 

We are currently developing a Java based Reinforcement Platform in [DJL](https://github.com/awslabs/djl) and can be easily integrate with this project. Are you open to have some time for a collaboration of a RL Agent?

**Comment by kingyuluk** [comment]
Yes, I'd glad to collaborate with you. I thought about training this game with deep learning before.

**Comment by lanking520** [comment]
Thanks for your interest! I will keep you posted once we have some prelimiary feature done.

**Comment by kingyuluk** [comment]
Thank you, I'm looking forward to it.

**Comment by lanking520** [comment]
Here is an example for you to start with:

[Train TicTacToe](https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/training/TrainTicTacToe.java)

We implemented DQN applied to this example for Agent to play tictactoe. There will be some integration work to make a FlappyAgent and connect to the RL interface.

You may need something like: [RL Environment](https://github.com/awslabs/djl/blob/master/examples/src/main/java/ai/djl/examples/training/TicTacToe.java) that can help to feed the framedata for Agent to learn. 

Here is the related implemenation

[Paper](http://cs231n.stanford.edu/reports/2016/pdfs/111_Report.pdf)

[RL Flappy bird](https://github.com/kyokin78/rl-flappybird)

Once you finish reading on the material and DJL's implementation, please let me know if you have some part not understanding.

**Comment by kingyuluk** [comment]
Hi，I am currently trying to use DJL to have RL feature into Flappy Bird. 

According to the link you provide and the DJL official documentation. I have refactored the code and make a agent and connect to the RL interface.

But I get problem when I passing a 4-channel 80*80 image through the net.

**Comment by zachgk** [comment]
Hi @kingyuluk. I took a look at your RL and have a few suggestions:

- Try using the version of RL training from DJL master/nightly snapshots. It has a number of updates compared to the last release.
- It looks like DQN.java is missing a call to trainer.step() on line 77
- For visual games, it is often worth it to make the graphics optional. Running the training without graphics is much faster.

**Comment by kingyuluk** [comment]
Thanks for your suggestions @zachgk .

I have modified my code according to your suggestion. But there are still some problems, the network doesn’t seem to be trained properly. 

In QAgent.java,  the result of line 86 is always 0.

**Comment by kingyuluk** [comment]
@zachgk thank you very much for your suggestions, I modified my code according to your suggestion.

And I have completed the project that integrates the Deep Java Library (DJL) to use DQN to train agents:
[RL-FlappyBird](https://github.com/kingyuluk/RL-FlappyBird)
