### ISSUE TITLE
It shoud be getKeyCode,not getKeyChar

### ISSUE THREAD

**Issue by jinmu333** [kingyuluk/FlappyBird#9]
https://github.com/kingyuluk/FlappyBird/blob/eb44ec32e3a6fd5fa13da512fe03e598aaf18d20/src/main/java/com/kingyu/flappybird/app/Game.java#L69

**Comment by kingyuluk** [comment]
For the space bar, getKeyCode and getKeyChar return the same value.

**Comment by dreamhunter2333** [comment]
> For the space bar, getKeyCode and getKeyChar return the same value, and you're right, getKeyCode a is more appropriate.

Thanks，I'm leaning Java by you project
